apiVersion: apps/v1
kind: Deployment
metadata:
  name: folding-at-home-gpu
  namespace: dev
  labels:
    app: folding-at-home-gpu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: folding-at-home-gpu
  template:
    metadata:
      labels:
        app: folding-at-home-gpu
    spec:
      containers:
      - name: folding-at-home-gpu
        image: richarvey/foldingathome:gpu
        imagePullPolicy: Always
        ports:
        - containerPort: 7396
        resources:
          requests:
            memory: "2048Mi"
          limits:
            memory: "2048Mi"
            nvidia.com/gpu: 1
